---
- hosts: local
  vars:
  - ubuntu_release: trusty

  tasks:
  - name: Update the repositories
    apt: update_cache=true

  - name: Run apt-get upgrade
    apt: upgrade=safe

  - name: Install fail2ban
    apt: pkg=fail2ban state=installed

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify: Restart sshd

  - name: Install unattended-upgrades
    apt: pkg=unattended-upgrades state=installed

  - name: Adjust APT update intervals
    copy: src=config/apt_periodic dest=/etc/apt/apt.conf.d/10periodic

  - name: Make sure unattended-upgrades only installs from $ubuntu_release-security
    lineinfile: dest=/etc/apt/apt.conf.d/50unattended-upgrades regexp="$ubuntu_release-updates" state=absent

  handlers:
  - name: Restart sshd
    service: name=ssh state=restarted
