---
- hosts: local
  vars:
  - ssh_users:
    - luke

  tasks:
  - name: Update the repositories
    apt: update_cache=true

  - name: Run apt-get upgrade
    apt: upgrade=safe

  - name: Install fail2ban
    apt: pkg=fail2ban state=installed
    
  - name: Install open-vm-tools
    apt: pkg=open-vm-tools state=installed
    
  - name: Set up authorized_keys for meeeeselfffffff.
    authorized_key: user=luke
                    key="{{ item }}"
    with_file:
    - public_keys/luke.pub

  - name: Install unattended-upgrades
    apt: pkg=unattended-upgrades state=installed

  - name: Turn on unattended-upgrades
    copy: src=config/20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades

  - name: Tell unattended-upgrades what to upgrade
    copy: src=config/50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades
  
  - name: Disable Password SSH Auth
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify: Restart ssh

  handlers:
  - name: Restart ssh
    service: name=ssh state=restarted
