---
- hosts: local
  vars:
  - ssh_users: {{item}}
    with_items:
    - luke

  tasks:
  - name: Update the repositories
    apt: update_cache=true

  - name: Run apt-get upgrade
    apt: upgrade=safe

  - name: Install fail2ban
    apt: pkg=fail2ban state=installed

  - name: Install open-vm-tools
    apt: pkg=open-vm-tools state=installed

  - name: Install user SSH keys
    authorized_key: user={{item}} key={{item}}.pub
    with_items:
    - $ssh_users

  - name: Disallow password authentication
    lineinfile: dest=/etc/ssh/sshd_config regexp="^PasswordAuthentication" line="PasswordAuthentication no" state=present
    notify: Restart sshd

  - name: Install unattended-upgrades
    apt: pkg=unattended-upgrades state=installed

  - name: Turn on unattended-upgrades
    copy: src=config/20auto-upgrades dest=/etc/apt/apt.conf.d/20auto-upgrades

  - name: Tell unattended-upgrades what to upgrade
    copy: src=config/50unattended-upgrades dest=/etc/apt/apt.conf.d/50unattended-upgrades

  handlers:
  - name: Restart sshd
    service: name=ssh state=restarted
